---
title: "Final Grade Reflection"
author: Jake McDonald
format: pdf
editor: visual
---

I believe that I deserve a B- in the class.

edits:

LAB 9

-   Include port revisions

LAB 7

-   include port revisions

LAB 4

-   include final summary revision

## Learning Target (11/23), with possible 4 on the way, 2 off the table

-   **WD-1:** I can import data from a variety of formats (e.g., csv, xlsx, txt, etc.).

    -   practice activity week 2 data import

-   **WD-2:** I can select necessary columns from a dataset.

    -   Challenge 3, #1

-   **WD-3:** I can filter rows from a dataframe for a variety of data types (e.g., numeric, integer, character, factor, date).

    -   Lab 3, #12

-   **WD-4: I can modify existing variables and create new variables in a dataframe for a variety of data types (e.g., numeric, integer, character, factor, date).**

    -   Challenge 3 #1, Lab 7 Part One Task 2, Task 5, Lab 9 #3

-   **WD-5: I can use mutating joins to combine multiple dataframes.**

    -   Lab 4, #2

-   **WD-6: I can use filtering joins to filter rows from a dataframe.**

    -   Lab 4, #2

-   **WD-7: I can pivot dataframes from long to wide and visa versa**

    -   Lab 4, #6, #7

<!-- -->

-   **R-1:** I can create a professional looking, reproducible analysis using RStudio projects, Quarto documents, and the here package.

    -   Lab 9

-   **R-2:** I can write well documented and tidy code.

    -   Lab 7, \#

-   **R-3:** I can write robust programs that are resistant to changes in inputs.

    -   Lab

-   **DVS-1:** I can create visualizations for a variety of variable types**.**

    -   Lab 7 - Part 1, Task 2

-   **DVS-2:** I use plot modifications to make my visualization clear to the reader.

    -   Lab 9 - Section 5, #1

-   **DVS-3:** I show creativity in my visualizations

    -   Lab 9 - Section 5, #1

-   **DVS-4:** I can calculate numerical summaries of variables.

    -   Lab

-   **DVS-5:** I can find summaries of variables across multiple groups.

    -   Challenge 3, #2

-   **DVS-6:** I can create tables which make my summaries clear to the reader.

    -   Lab

-   **DVS-7:** I show creativity in my tables.

    -   lab 9?

-   **PE-1:** I can write concise code which does not repeat itself.

    -   Lab, iteration function

-   **PE-2:** I can write functions to reduce repetition in my code.

    -   Lab, functions

-   **PE-3:**I can use iteration to reduce repetition in my code

    -   Lab,

-   **PE-4: I can use modern tools when carrying out my analysis.**

    -   Lab

-   **DSM-1:** I can simulate data from a variety of probability models.

    -   Practice Activity 9, #3

-   **DSM-2:** I can fit a linear regression and extract necessary summary measures.

    -   Lab 9, \#

Although I have demonstrated understanding of of the learning objectives, I haven't been giving enough attention to the revisions, I haven't been able to do peer reviews as of late because my labs have been getting submitted late, and I'm overall not putting enough effort into this class. I hope to raise my grade to a C in the final portfolio, but as of now I don't have enough proof to say that I have mastered more than half of the content in the class. As of now, I can select, filter, and modify existing variables so that I can pull out and visualize the correct information. This can be seen in Lab 3 when I mutate the ethnic variable to "white" and "non-white", and when I use filter, group by, and slice min/max. Additionally, I converted the variables sex and ethnic to factors. Furthermore, I can use the summarize function to pull out things like mean_weight as seen in Lab 5. I can also use mutating joins as seen in Lab 4, which is also an example of efficient and tidy code that doesn't repeat itself while also reducing repetition. I also used a filtering join in Lab 4 when I used semi_join to pull out the major regions in the data. For creating a professional looking quarto document that has also reflected my growth as a data scientist, I refer to my Lab 3 revisions. I revised the lab so that library outputs are no longer present in the html file, I added more to the description of the data, and used other functions than print to display information. I need to work writing robust programs that are resistant to changes in inputs because I mainly use the names of variables. I can also create visualizations for a variety of variable types and add creative elements to them. In Lab 2, I was able to create scatterplots for two numeric variables. In Lab 5, I learned about how to reorder the box plots to increase insightfulness and moved the y-axis to the top of the graph so that it is more legible. I also collapsed Monday through Friday into the groups 'weekend' and 'weekday' to allow viewers to see the difference more clearly. In Lab 4, I used columns to represent the proportion of avocado sold in each of the Californian regions. Although my graph did not match the one in the instructions, I came very close and will fix it on the final draft of the portfolio. Regarding committing to continued learning, I feel as though I have been slacking in that aspect. I do feel like I have grown as a team member and leader, by helping facilitate the group work. I listen to my team members respectfully and help when needed. I did miss one Thursday, which is also why I believe that I am sitting at a D. I have contributed to creating a respectful classroom learning by not making stereotypes about people and truly listening and communicating with those around me. Furthermore, I have been active in my teams group chat and have worked with them outside of class to help them and myself with various activities. As a business major, it has been awesome to be surrounded by so many different majors and skill sets. I don't feel like I have been accomplishing all the goals that I outlined for myself because I believe I have been lacking in effort.

## **Collaborative Group Member**

## **Peer-Code Review**

## 
